[features]
seeds = false
skip-lint = false
[programs.localnet]
frcnt = "21ydYig5uj46RJ36mbU1aooxvtekcEQbW1MgcYJNEdNi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ravigarg/my-local-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
